// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package todoview

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Add() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form class=\"flex flex-row gap-1 w-full\" hx-post=\"/todos/add\" hx-target=\"#todo-list\" hx-swap=\"beforeend\" hx-on::after-request=\" if(event.detail.successful) this.reset()\"><input type=\"text\" name=\"content\" class=\"flex flex-grow h-10 shadow appearance-none border rounded py-2 px-3 text-gray-700 bg-gray-100 leading-tight\"> <button type=\"submit\" class=\"flex h-10 w-16 justify-center bg-green-600 hover:bg-green-700 focus:outline-none text-white bg-green-700font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2\">Add</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
